# Generated by Django 4.1.3 on 2023-05-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('cilindraje', models.CharField(max_length=50)),
            ],
        ),
    ]
