# Generated by Django 4.1.3 on 2023-06-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaZapatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatos',
            name='tallaZ',
            field=models.CharField(default='', max_length=255),
        ),
    ]
